# Generated by Django 6.0.1 on 2026-02-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='original_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
