# Generated by Django 6.0.1 on 2026-02-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_links_is_active_links_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicks',
            name='referrer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
